{% set name = "panel-graphic-walker" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/panel_graphic_walker/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: ae89a4a22f2db53b0bc48a2c86b95813277e3209b73b39edd306a0c8d2dc9cb7

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - panel >=1.6.1
    - packaging
    - narwhals
    - pip
    # nodejs/esbuild required, see https://github.com/panel-extensions/panel-graphic-walker/blob/main/DEVELOPER_GUIDE.md
    - nodejs >=18
    - esbuild
  run:
    - python
    - panel >=1.6.1
    - narwhals
  run_constrained:
    - pygwalker >=0.4.9.11

test:
  imports:
    - panel_gwalker
  source_files:
    - tests
  commands:
    - pip check
  requires:
    - pip
# pytesting is available, but requires the building of dependencies that are not available.
# we will keep simple testing for now.

about:
  home: https://github.com/panel-extensions/panel-graphic-walker
  summary: A project providing a Graphic Walker Pane for use with HoloViz Panel.
  description: |
    panel-graphic-walker is a Panel extension providing Graphic Walker
    integration for data visualization. It allows users to create interactive
    visual exploratory data analysis interfaces directly in Panel dashboards.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  doc_url: https://github.com/panel-extensions/panel-graphic-walker/blob/main/README.md
  dev_url: https://github.com/panel-extensions/panel-graphic-walker

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
  recipe-maintainers:
    - philippjfr
